# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chen/MyEngineServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chen/MyEngineServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chen/MyEngineServer/CMakeFiles /home/chen/MyEngineServer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chen/MyEngineServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyEngineServer

# Build rule for target.
MyEngineServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyEngineServer
.PHONY : MyEngineServer

# fast build rule for target.
MyEngineServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/build
.PHONY : MyEngineServer/fast

# target to build an object file
src/MessageManager/HandleMessage.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/MessageManager/HandleMessage.o
.PHONY : src/MessageManager/HandleMessage.o

# target to preprocess a source file
src/MessageManager/HandleMessage.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/MessageManager/HandleMessage.i
.PHONY : src/MessageManager/HandleMessage.i

# target to generate assembly for a file
src/MessageManager/HandleMessage.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/MessageManager/HandleMessage.s
.PHONY : src/MessageManager/HandleMessage.s

# target to build an object file
src/MessageManager/MessageManager.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/MessageManager/MessageManager.o
.PHONY : src/MessageManager/MessageManager.o

# target to preprocess a source file
src/MessageManager/MessageManager.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/MessageManager/MessageManager.i
.PHONY : src/MessageManager/MessageManager.i

# target to generate assembly for a file
src/MessageManager/MessageManager.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/MessageManager/MessageManager.s
.PHONY : src/MessageManager/MessageManager.s

# target to build an object file
src/MyEngineServer.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/MyEngineServer.o
.PHONY : src/MyEngineServer.o

# target to preprocess a source file
src/MyEngineServer.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/MyEngineServer.i
.PHONY : src/MyEngineServer.i

# target to generate assembly for a file
src/MyEngineServer.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/MyEngineServer.s
.PHONY : src/MyEngineServer.s

# target to build an object file
src/MyMysql/MyMysql.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/MyMysql/MyMysql.o
.PHONY : src/MyMysql/MyMysql.o

# target to preprocess a source file
src/MyMysql/MyMysql.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/MyMysql/MyMysql.i
.PHONY : src/MyMysql/MyMysql.i

# target to generate assembly for a file
src/MyMysql/MyMysql.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/MyMysql/MyMysql.s
.PHONY : src/MyMysql/MyMysql.s

# target to build an object file
src/tcp/MyTcpSocket.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/tcp/MyTcpSocket.o
.PHONY : src/tcp/MyTcpSocket.o

# target to preprocess a source file
src/tcp/MyTcpSocket.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/tcp/MyTcpSocket.i
.PHONY : src/tcp/MyTcpSocket.i

# target to generate assembly for a file
src/tcp/MyTcpSocket.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyEngineServer.dir/build.make CMakeFiles/MyEngineServer.dir/src/tcp/MyTcpSocket.s
.PHONY : src/tcp/MyTcpSocket.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MyEngineServer"
	@echo "... src/MessageManager/HandleMessage.o"
	@echo "... src/MessageManager/HandleMessage.i"
	@echo "... src/MessageManager/HandleMessage.s"
	@echo "... src/MessageManager/MessageManager.o"
	@echo "... src/MessageManager/MessageManager.i"
	@echo "... src/MessageManager/MessageManager.s"
	@echo "... src/MyEngineServer.o"
	@echo "... src/MyEngineServer.i"
	@echo "... src/MyEngineServer.s"
	@echo "... src/MyMysql/MyMysql.o"
	@echo "... src/MyMysql/MyMysql.i"
	@echo "... src/MyMysql/MyMysql.s"
	@echo "... src/tcp/MyTcpSocket.o"
	@echo "... src/tcp/MyTcpSocket.i"
	@echo "... src/tcp/MyTcpSocket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

